export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';

export const COUNTER_GET_DATA_API_REQUEST = 'COUNTER_GET_DATA_API_REQUEST';
export const COUNTER_GET_DATA_API_SUCCESS = 'COUNTER_GET_DATA_API_SUCCESS';
export const COUNTER_GET_DATA_API_FAILURE = 'COUNTER_GET_DATA_API_FAILURE';
