export const POSTS_GET_POST_API_REQUEST = 'POSTS_GET_POST_API_REQUEST';
export const POSTS_GET_POST_API_SUCCESS = 'POSTS_GET_POST_API_SUCCESS';
export const POSTS_GET_POST_API_FAILURE = 'POSTS_GET_POST_API_FAILURE';

export const POSTS_GET_POSTS_API_REQUEST = 'POSTS_GET_POSTS_API_REQUEST';
export const POSTS_GET_POSTS_API_SUCCESS = 'POSTS_GET_POSTS_API_SUCCESS';
export const POSTS_GET_POSTS_API_FAILURE = 'POSTS_GET_POSTS_API_FAILURE';
